/-
# Riemann Surfaces: Bridge to Algebra

Connections between Riemann surfaces and algebraic geometry:
- Function field M(X): a finitely generated field extension of ℂ
  of transcendence degree 1
- The divisor class group Cl(X) ≅ Pic(X)
- The Picard variety Pic⁰(X) ≅ Jac(X) as abelian varieties
- Meromorphic functions ↔ rational functions on the algebraic model
- Dedekind-Weber: equivalence between RS function fields and
  abstract algebraic function fields of one variable over ℂ
-/

import MiniRiemannSurfaces.Core.Basic

namespace MiniRiemannSurfaces

/-! ## Function Field of a Riemann Surface -/

/-- The field M(X) of meromorphic functions on a compact Riemann surface
X is a finitely generated extension of ℂ of transcendence degree 1.

Conversely (Dedekind-Weber), every finitely generated field extension
K/ℂ of transcendence degree 1 is the function field of a unique
(normal) compact Riemann surface. -/
axiom functionFieldDegree (X : RiemannSurface) : True

/-- M(X) is finitely generated over ℂ with transcendence degree 1.
For the Riemann sphere ℂ̂, M(ℂ̂) = ℂ(z) (rational functions). -/
def functionField (X : RiemannSurface) : String := s!"M({genus X})"

/-- The genus of X can be recovered from M(X) via:
- g = 0 iff M(X) ≅ ℂ(z) (rational function field)
- g = 1 iff M(X) has exactly one valuation of each degree
- g ≥ 2: genus is the minimal integer such that M(X) is generated
  by an element with g+1 poles -/
axiom genusFromFunctionField (X : RiemannSurface) : True

#eval "Function field of Riemann sphere: ℂ(z)"

/-! ## Divisor Class Group -/

/-- The divisor class group Cl(X) = Div(X) / PDiv(X) is the quotient
of the divisor group by the subgroup of principal divisors.
For a compact Riemann surface, Cl⁰(X) ≅ Jac(X). -/
structure DivisorClassGroup (X : RiemannSurface) where
  divisors : Type            -- Div(X)
  principalDivisors : Type   -- PDiv(X)
  classGroup : Type          -- Cl(X)
  deriving Repr

/-- The degree homomorphism deg: Cl(X) → ℤ has kernel
Cl⁰(X) = divisors of degree 0 modulo principal divisors. -/
axiom classGroupDegreeExactSequence (X : RiemannSurface) : True

/-! ## Picard Variety -/

/-- The Picard variety Pic(X) parametrizes holomorphic line bundles
on X up to isomorphism. Pic⁰(X) ≅ Jac(X) as abelian varieties. -/
structure PicardVariety (X : RiemannSurface) where
  lineBundles : Type
  degree : ℤ
  deriving Repr

/-- The Néron-Severi group NS(X) = Pic(X)/Pic⁰(X) ≅ ℤ for a
Riemann surface (generated by the degree). -/
def neronSeveriGroup (X : RiemannSurface) : String := "ℤ"

/-- The exponential exact sequence:
0 → ℤ → O_X → O_X^* → 0
induces H¹(X, O_X^*) ≅ Pic(X), and the long exact sequence gives
0 → Jac(X) → Pic(X) → ℤ → 0 -/
axiom exponentialSequence (X : RiemannSurface) : True

#eval "Divisor class group Cl(X) defined"
#eval "Pic⁰(X) ≅ Jac(X): degree-0 line bundles"
#eval "NS(X) ≅ ℤ for any compact RS"

end MiniRiemannSurfaces
